export const mockStops = [
  {
    stop_id: "1",
    address: "Via Girolamo Dandini, 10, Monteverde, Roma",
    latitude: 41.8751,
    longitude: 12.4589,
    isUserLocation: true,
  },
  {
    stop_id: "2",
    address: "Via Portuense, 102, Monteverde, Roma",
    latitude: 41.8728,
    longitude: 12.4612,
    isUserLocation: false,
  },
  {
    stop_id: "3",
    address: "Piazza di San Cosimato, Trastevere, Roma",
    latitude: 41.8876,
    longitude: 12.4701,
    isUserLocation: false,
  },
  {
    stop_id: "4",
    address: "Via Galvani, 24, Testaccio, Roma",
    latitude: 41.8782,
    longitude: 12.4765,
    isUserLocation: false,
  },
  {
    stop_id: "5",
    address: "Via Marmorata, 47, Testaccio, Roma",
    latitude: 41.8798,
    longitude: 12.4789,
    isUserLocation: false,
  },
  {
    stop_id: "6",
    address: "Via Ostiense, 63, Ostiense, Roma",
    latitude: 41.8734,
    longitude: 12.4802,
    isUserLocation: false,
  },
  {
    stop_id: "7",
    address: "Via di Monte Testaccio, 30, Testaccio, Roma",
    latitude: 41.8771,
    longitude: 12.4752,
    isUserLocation: false,
  },
  {
    stop_id: "8",
    address: "Viale di Trastevere, 181, Trastevere, Roma",
    latitude: 41.8854,
    longitude: 12.4723,
    isUserLocation: false,
  },
  {
    stop_id: "9",
    address: "Via Ettore Rolli, 6, Monteverde, Roma",
    latitude: 41.8764,
    longitude: 12.4598,
    isUserLocation: false,
  },
  {
    stop_id: "10",
    address: "Via Nicola Zabaglia, 15, Testaccio, Roma",
    latitude: 41.8789,
    longitude: 12.4778,
    isUserLocation: false,
  },
  {
    stop_id: "11",
    address: "Piazza Testaccio, 48, Testaccio, Roma",
    latitude: 41.8776,
    longitude: 12.4768,
    isUserLocation: false,
  },
  {
    stop_id: "12",
    address: "Via di Porta San Paolo, 10, Ostiense, Roma",
    latitude: 41.8756,
    longitude: 12.4812,
    isUserLocation: false,
  },
  {
    stop_id: "13",
    address: "Via della Lungaretta, 65, Trastevere, Roma",
    latitude: 41.8893,
    longitude: 12.4721,
    isUserLocation: false,
  },
  {
    stop_id: "14",
    address: "Via Carini, 58, Monteverde, Roma",
    latitude: 41.8743,
    longitude: 12.4576,
    isUserLocation: false,
  },
  {
    stop_id: "15",
    address: "Via Beniamino Franklin, 2, Ostiense, Roma",
    latitude: 41.8712,
    longitude: 12.4798,
    isUserLocation: false,
  },
  {
    stop_id: "16",
    address: "Piazza di Santa Maria in Trastevere, 3, Trastevere, Roma",
    latitude: 41.8897,
    longitude: 12.4698,
    isUserLocation: false,
  },
  {
    stop_id: "17",
    address: "Via dei Vascellari, 29, Trastevere, Roma",
    latitude: 41.8869,
    longitude: 12.4712,
    isUserLocation: false,
  },
  {
    stop_id: "18",
    address: "Via Luca della Robbia, 15, Testaccio, Roma",
    latitude: 41.8801,
    longitude: 12.4759,
    isUserLocation: false,
  },
  {
    stop_id: "19",
    address: "Via Ramazzini, 45, Monteverde, Roma",
    latitude: 41.8738,
    longitude: 12.4621,
    isUserLocation: false,
  },
  {
    stop_id: "20",
    address: "Via Giovanni da Empoli, 8, Ostiense, Roma",
    latitude: 41.8689,
    longitude: 12.4823,
    isUserLocation: false,
  },
  {
    stop_id: "21",
    address: "Via Fratelli Bonnet, 6, Monteverde, Roma",
    latitude: 41.8779,
    longitude: 12.4634,
    isUserLocation: false,
  },
  {
    stop_id: "22",
    address: "Via Alessandro Volta, 34, Testaccio, Roma",
    latitude: 41.8768,
    longitude: 12.4743,
    isUserLocation: false,
  },
  {
    stop_id: "23",
    address: "Lungotevere Ripa, 12, Trastevere, Roma",
    latitude: 41.8842,
    longitude: 12.4778,
    isUserLocation: false,
  },
  {
    stop_id: "24",
    address: "Via Padre Semeria, 22, Monteverde, Roma",
    latitude: 41.8792,
    longitude: 12.4587,
    isUserLocation: false,
  },
];
